"require strict";

module.exports = {
  STORE_PLAYLISTS_FOLLOWED_BY_USER_INTO_STORE: "STORE_PLAYLISTS_FOLLOWED_BY_USER_INTO_STORE",

  NOTIFY_VIEWED_SONG_STORE_OF_NEW_SONG_LIKE: "NOTIFY_VIEWED_SONG_STORE_OF_NEW_SONG_LIKE",

  NOTIFY_VIEWED_SONG_STORE_OF_REMOVED_SONG_LIKE: "NOTIFY_VIEWED_SONG_STORE_OF_REMOVED_SONG_LIKE",

  NOTIFY_VIEWED_SONG_STORE_OF_NEW_SONG_RATING: "NOTIFY_VIEWED_SONG_STORE_OF_NEW_SONG_RATING",

  STORE_ALBUMS_FOLLOWED_BY_USER_INTO_FOLLOWED_ALBUMS_STORE: "STORE_ALBUMS_FOLLOWED_BY_USER_INTO_FOLLOWED_ALBUMS_STORE",

  NOTIFY_VIEWED_SONG_STORE_OF_UPDATED_LIST_OF_SONGS_FOR_ALBUM: "NOTIFY_VIEWED_SONG_STORE_OF_UPDATED_LIST_OF_SONGS_FOR_ALBUM",

  NOTIFY_VIEWED_SONG_STORE_THAT_ALBUM_HAS_BEEN_FOLLOWED: "NOTIFY_VIEWED_SONG_STORE_THAT_ALBUM_HAS_BEEN_FOLLOWED",

  NOTIFY_VIEWED_SONG_STORE_THAT_ALBUM_HAS_BEEN_UNFOLLOWED: "NOTIFY_VIEWED_SONG_STORE_THAT_ALBUM_HAS_BEEN_UNFOLLOWED",

  NOTIFY_FRIENDS_STORE_OF_UPDATED_SOCIAL_CONTENT: "NOTIFY_FRIENDS_STORE_OF_UPDATED_SOCIAL_CONTENT",

  NOTIFY_VIEWED_SONG_STORE_OF_UPDATED_LIST_OF_SONGS_FOR_PLAYLIST: "NOTIFY_VIEWED_SONG_STORE_OF_UPDATED_LIST_OF_SONGS_FOR_PLAYLIST",

  NOTIFY_VIEWED_SONG_STORE_OF_REMOVED_SONG_LIKE_FROM_WITHIN_SONG_LIKES_PLAYLIST: "NOTIFY_VIEWED_SONG_STORE_OF_REMOVED_SONG_LIKE_FROM_WITHIN_SONG_LIKES_PLAYLIST",

  NOTIFY_FRIENDS_STORE_OF_NEW_FRIENDSHIP: "NOTIFY_FRIENDS_STORE_OF_NEW_FRIENDSHIP",

  NOTIFY_FRIENDS_STORE_OF_DESTROYED_FRIENDSHIP: "NOTIFY_FRIENDS_STORE_OF_DESTROYED_FRIENDSHIP",

  ADD_SONG_TO_PLAYLIST_IF_RELEVANT: "ADD_SONG_TO_PLAYLIST_IF_RELEVANT",

  REMOVE_SONG_FROM_PLAYLIST_IF_RELEVANT: "REMOVE_SONG_FROM_PLAYLIST_IF_RELEVANT",

  RESET_QUEUED_SONGS_WITH_NEW_SONGS_FROM_VIEWED_SONG_STORE: "RESET_QUEUED_SONGS_WITH_NEW_SONGS_FROM_VIEWED_SONG_STORE",

  START_SONG_PLAY: "START_SONG_PLAY",

  PAUSE_CURRENT_SONG_PLAY: "PAUSE_CURRENT_SONG_PLAY",

  INITIALIZE_AUDIO_PLAYER: "INITIALIZE_AUDIO_PLAYER",

  ASYNC_SONGS_IN_MEMORY_CHANGE: "ASYNC_SONGS_IN_MEMORY_CHANGE",

  RESUME_CURRENT_SONG_PLAY: "RESUME_CURRENT_SONG_PLAY",

  MOVE_FORWARD_IN_QUEUED_SONGS: "MOVE_FORWARD_IN_QUEUED_SONGS",

  RESET_SONG_POSITION_TO_ZERO: "RESET_SONG_POSITION_TO_ZERO",

  MOVE_TO_SONG_POSITION: "MOVE_TO_SONG_POSITION",

  SET_VOLUME: "SET_VOLUME",

  ADD_NEWLY_RETRIEVED_RADIO_SONGS_TO_QUEUE: "ADD_NEWLY_RETRIEVED_RADIO_SONGS_TO_QUEUE",

  RESET_QUEUED_SONGS_WITH_NEW_SONGS_FROM_RADIO_API: "RESET_QUEUED_SONGS_WITH_NEW_SONGS_FROM_RADIO_API",

  NOTIFY_VIEWED_SONG_STORE_OF_UPDATED_LIST_OF_SONGS_FOR_ARTIST: "NOTIFY_VIEWED_SONG_STORE_OF_UPDATED_LIST_OF_SONGS_FOR_ARTIST",

  STORE_ARTISTS_FOLLOWED_BY_USER_INTO_FOLLOWED_ARTISTS_STORE: "STORE_ARTISTS_FOLLOWED_BY_USER_INTO_FOLLOWED_ARTISTS_STORE",

  NOTIFY_VIEWED_SONG_STORE_THAT_ARTIST_HAS_BEEN_FOLLOWED: "NOTIFY_VIEWED_SONG_STORE_THAT_ARTIST_HAS_BEEN_FOLLOWED",

  NOTIFY_VIEWED_SONG_STORE_THAT_ARTIST_HAS_BEEN_UNFOLLOWED: "NOTIFY_VIEWED_SONG_STORE_THAT_ARTIST_HAS_BEEN_UNFOLLOWED",

  NOTIFY_QUEUED_SONG_STORE_OF_NEW_SONG_LIKE: "NOTIFY_QUEUED_SONG_STORE_OF_NEW_SONG_LIKE",

  NOTIFY_QUEUED_SONG_STORE_OF_REMOVED_SONG_LIKE: "NOTIFY_QUEUED_SONG_STORE_OF_REMOVED_SONG_LIKE",

  NOTIFY_RADIO_SONG_STORE_OF_NEW_SONG_LIKE: "NOTIFY_RADIO_SONG_STORE_OF_NEW_SONG_LIKE",

  NOTIFY_QUEUED_SONG_STORE_OF_REMOVED_SONG_LIKE: "NOTIFY_QUEUED_SONG_STORE_OF_REMOVED_SONG_LIKE",

  NOTIFY_RADIO_SONG_STORE_OF_NEW_SONG_RATING: "NOTIFY_RADIO_SONG_STORE_OF_NEW_SONG_RATING",

  NOTIFY_QUEUED_SONG_STORE_OF_NEW_SONG_RATING: "NOTIFY_QUEUED_SONG_STORE_OF_NEW_SONG_RATING",

  ASYNC_FORCE_SONGS_IN_MEMORY_UPDATE: "ASYNC_FORCE_SONGS_IN_MEMORY_UPDATE",

  ASYNC_FORCE_QUEUED_SONGS_STORE_UPDATE: "ASYNC_FORCE_QUEUED_SONGS_STORE_UPDATE",

  ASYNC_FORCE_UPCOMING_RADIO_SONGS_STORE_UPDATE: "ASYNC_FORCE_UPCOMING_RADIO_SONGS_STORE_UPDATE",

  RECIEVE_SEARCH_RESULTS: "RECIEVE_SEARCH_RESULTS",

  STORE_FEATURED_CONTENT_IN_FEATURED_CONTENT_STORE: "STORE_FEATURED_CONTENT_IN_FEATURED_CONTENT_STORE",
};
