"require strict";

module.exports = {
  NO_MODAL_CONTENT: "NO_MODAL_CONTENT",

  NEW_PLAYLIST_MODAL_CONTENT: "NEW_PLAYLIST_MODAL_CONTENT",

  SONG_MENU_MODAL_CONTENT: "SONG_MENU_MODAL_CONTENT",

  NO_LOOP_MODE: "NO LOOP MODE",
  LOOP_PLAYLIST_MODE: "LOOP PLAYLIST MODE",
  LOOP_SONG_MODE: "LOOP SONG MODE",

};
